### ISSUE TITLE
Local Kurjun does not return templates from cache when there is no Internet connection

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/gorjun#99]
Seems local Kurjun does not cache templates and fails to return template list if peer has not Internet connection 

karaf error log:

`2017-08-15 12:42:01,963 | ERROR | ool-394-thread-1 | TemplateManagerImpl              | 212 - io.subutai.core.template.impl - 5.0.0 | Error getting templates from local Gorjun
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: SocketTimeoutException invoking http://localhost:8338/kurjun/rest/template/info?token: Read Timeout
	at org.apache.cxf.jaxrs.client.AbstractClient.checkClientException(AbstractClient.java:557)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.AbstractClient.preProcessResult(AbstractClient.java:539)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.doResponse(WebClient.java:1151)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1101)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:894)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.doInvoke(WebClient.java:865)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.invoke(WebClient.java:331)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.get(WebClient.java:357)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at io.subutai.core.template.impl.TemplateManagerImpl.getTemplates(TemplateManagerImpl.java:121)[212:io.subutai.core.template.impl:5.0.0]
	at io.subutai.core.template.impl.TemplateManagerImpl.getTemplate(TemplateManagerImpl.java:188)[212:io.subutai.core.template.impl:5.0.0]
	at Proxy5f92d45f_87d2_4063_a4de_3db6fb3a6e07.getTemplate(Unknown Source)[:]
	at Proxy28559bac_2f4a_4c77_b46c_cceaf2c51055.getTemplate(Unknown Source)[:]
	at io.subutai.core.localpeer.impl.LocalPeerImpl.prepareTemplates(LocalPeerImpl.java:816)[177:io.subutai.core.localpeer.impl:5.0.0]
	at Proxy7c3fbbf5_01c4_4421_92e2_d5a28545c460.prepareTemplates(Unknown Source)[:]
	at Proxy7c3fbbf5_01c4_4421_92e2_d5a28545c460.prepareTemplates(Unknown Source)[:]
	at Proxyb1ea8001_730d_4525_ba95_efe7c3b75f05.prepareTemplates(Unknown Source)[:]
	at io.subutai.core.environment.impl.workflow.creation.steps.helpers.PeerImportTemplateTask.call(PeerImportTemplateTask.java:60)[146:io.subutai.core.environment.impl:5.0.0]
	at io.subutai.core.environment.impl.workflow.creation.steps.helpers.PeerImportTemplateTask.call(PeerImportTemplateTask.java:19)[146:io.subutai.core.environment.impl:5.0.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)[:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)[:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)[:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745)[:1.8.0_111]
Caused by: java.net.SocketTimeoutException: SocketTimeoutException invoking http://localhost:8338/kurjun/rest/template/info?token: Read Timeout
	at sun.reflect.GeneratedConstructorAccessor236.newInstance(Unknown Source)[:1.8.0_111]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)[:1.8.0_111]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)[:1.8.0_111]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.mapException(HTTPConduit.java:1365)[97:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1349)[97:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.close(AsyncHTTPConduit.java:414)[100:org.apache.cxf.cxf-rt-transports-http-hc:3.1.0]
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)[92:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:652)[97:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)[92:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[92:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.jaxrs.client.AbstractClient.doRunInterceptorChain(AbstractClient.java:624)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	at org.apache.cxf.jaxrs.client.WebClient.doChainedInvocation(WebClient.java:1100)[99:org.apache.cxf.cxf-rt-rs-client:3.1.0]
	... 20 more
Caused by: java.net.SocketTimeoutException: Read Timeout
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.getHttpResponse(AsyncHTTPConduit.java:637)[100:org.apache.cxf.cxf-rt-transports-http-hc:3.1.0]
	at org.apache.cxf.transport.http.asyncclient.AsyncHTTPConduit$AsyncWrappedOutputStream.getResponseCode(AsyncHTTPConduit.java:722)[100:org.apache.cxf.cxf-rt-transports-http-hc:3.1.0]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1560)[97:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1533)[97:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1336)[97:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	... 27 more`

**Comment by soffokl** [comment]
Unfortunately, Kurjun can't work without Internet connection. We have nothing to do with it.
